import type { User, ChartData } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alex Rivera",
    email: "admin@insightflow.io",
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    role: "admin",
    status: "active",
    joinedAt: "2025-01-15",
  },
  {
    id: "2",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    image: "https://avatars.githubusercontent.com/u/2?v=4",
    role: "viewer",
    status: "active",
    joinedAt: "2025-02-20",
  },
  {
    id: "3",
    name: "Morgan Chen",
    email: "morgan.chen@example.com",
    image: "https://avatars.githubusercontent.com/u/3?v=4",
    role: "viewer",
    status: "inactive",
    joinedAt: "2025-03-05",
  },
  {
    id: "4",
    name: "Sam Patel",
    email: "sam.patel@example.com",
    image: "https://avatars.githubusercontent.com/u/4?v=4",
    role: "admin",
    status: "active",
    joinedAt: "2025-01-28",
  },
  {
    id: "5",
    name: "Taylor Brooks",
    email: "taylor.brooks@example.com",
    image: "https://avatars.githubusercontent.com/u/5?v=4",
    role: "viewer",
    status: "active",
    joinedAt: "2025-04-10",
  },
  {
    id: "6",
    name: "Drew Wilson",
    email: "drew.wilson@example.com",
    image: "https://avatars.githubusercontent.com/u/6?v=4",
    role: "viewer",
    status: "inactive",
    joinedAt: "2025-02-14",
  },
  {
    id: "7",
    name: "Casey Morgan",
    email: "casey.morgan@example.com",
    image: "https://avatars.githubusercontent.com/u/7?v=4",
    role: "viewer",
    status: "active",
    joinedAt: "2025-03-22",
  },
  {
    id: "8",
    name: "Riley Kim",
    email: "riley.kim@example.com",
    image: "https://avatars.githubusercontent.com/u/8?v=4",
    role: "viewer",
    status: "active",
    joinedAt: "2025-04-01",
  },
  {
    id: "9",
    name: "Quinn Nguyen",
    email: "quinn.nguyen@example.com",
    image: "https://avatars.githubusercontent.com/u/9?v=4",
    role: "viewer",
    status: "inactive",
    joinedAt: "2025-01-05",
  },
  {
    id: "10",
    name: "Avery Thompson",
    email: "avery.admin@insightflow.io",
    image: "https://avatars.githubusercontent.com/u/10?v=4",
    role: "admin",
    status: "active",
    joinedAt: "2024-12-01",
  },
];

export const mrrChartData: ChartData[] = [
  { label: "May", value: 7200 },
  { label: "Jun", value: 8100 },
  { label: "Jul", value: 7800 },
  { label: "Aug", value: 9400 },
  { label: "Sep", value: 10200 },
  { label: "Oct", value: 9800 },
  { label: "Nov", value: 11000 },
  { label: "Dec", value: 10500 },
  { label: "Jan", value: 11800 },
  { label: "Feb", value: 12100 },
  { label: "Mar", value: 11600 },
  { label: "Apr", value: 12450 },
];

export const weeklyUsersData: ChartData[] = [
  { label: "Mon", value: 820 },
  { label: "Tue", value: 932 },
  { label: "Wed", value: 1100 },
  { label: "Thu", value: 1034 },
  { label: "Fri", value: 980 },
  { label: "Sat", value: 650 },
  { label: "Sun", value: 720 },
];

export const analyticsPageviewsData: ChartData[] = [
  { label: "May", value: 12400, secondary: 9800 },
  { label: "Jun", value: 14200, secondary: 11200 },
  { label: "Jul", value: 13800, secondary: 10900 },
  { label: "Aug", value: 16000, secondary: 13400 },
  { label: "Sep", value: 17500, secondary: 14200 },
  { label: "Oct", value: 16800, secondary: 13900 },
  { label: "Nov", value: 18900, secondary: 15600 },
  { label: "Dec", value: 17600, secondary: 14800 },
  { label: "Jan", value: 20200, secondary: 17100 },
  { label: "Feb", value: 21400, secondary: 18300 },
  { label: "Mar", value: 19800, secondary: 16900 },
  { label: "Apr", value: 22600, secondary: 19400 },
];

export const dashboardMetrics = {
  mrr: 12450,
  activeUsers: 1284,
  churnRate: 2.4,
  apiCalls: 48200,
};
